<?php

namespace Database\Seeders;

use App\Domains\Expenses\Services\ExpenseService;
use App\Domains\Property\Models\Property;
use App\Domains\Shared\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Auth;

/**
 * Realistic P6 demo data: utility meters, readings, expenses.
 * (Bills are generated by tests/E2E, not the seeder, to keep
 * demo tenant ledgers clean for other test suites.)
 */
class UtilityExpenseSeeder extends Seeder
{
    public function run(): void
    {
        if (\App\Domains\Utilities\Models\UtilityMeter::where('meter_number', 'like', 'DEMO-%')->exists()) {
            return; // idempotent
        }

        $admin = User::where('email', 'admin@ahmedestates.local')->firstOrFail();
        Auth::login($admin);

        $meters = app(\App\Domains\Utilities\Services\UtilityMeterService::class);
        $expenses = app(ExpenseService::class);

        $property = Property::firstOrFail();
        // R-101 has the active demo tenant lease (tenant portal user).
        $unit = \App\Domains\Property\Models\Unit::where('unit_number', 'R-101')->first()
            ?? \App\Domains\Property\Models\Unit::first();

        // Electricity meter on the tenant's unit.
        $elec = $meters->createMeter([
            'property_id' => $property->id,
            'unit_id' => $unit?->id,
            'meter_number' => 'DEMO-EL-001',
            'utility_type' => 'electricity',
            'unit_of_measure' => 'kWh',
            'installation_date' => '2025-01-01',
            'opening_reading' => 1000,
            'notes' => 'Demo meter.',
        ]);

        $meters->recordReading($elec, [
            'reading_date' => '2026-08-31',
            'reading_value' => 5200,
            'notes' => 'Demo: August reading.',
        ]);
        $meters->recordReading($elec, [
            'reading_date' => '2026-09-30',
            'reading_value' => 5480,
            'notes' => 'Demo: September reading.',
        ]);

        // Shared water meter on the property (no unit).
        $water = $meters->createMeter([
            'property_id' => $property->id,
            'meter_number' => 'DEMO-WA-001',
            'utility_type' => 'water',
            'unit_of_measure' => 'm3',
            'installation_date' => '2025-01-01',
            'opening_reading' => 200,
            'notes' => 'Demo: shared building meter.',
        ]);
        $meters->recordReading($water, [
            'reading_date' => '2026-09-30',
            'reading_value' => 260,
        ]);

        // Expenses: one posted, one draft.
        $vendor = \App\Domains\Maintenance\Models\MaintenanceVendor::first();

        $e1 = $expenses->create([
            'property_id' => $property->id,
            'vendor_id' => $vendor?->id,
            'category' => 'repairs',
            'description' => 'Demo: corridor lighting repair.',
            'expense_date' => '2026-09-15',
            'amount' => 12500,
            'notes' => 'Demo expense.',
        ]);
        $expenses->transition($e1, 'submitted');
        $expenses->transition($e1->fresh(), 'approved');
        $expenses->transition($e1->fresh(), 'posted');

        $expenses->create([
            'property_id' => $property->id,
            'category' => 'cleaning',
            'description' => 'Demo: deep cleaning of common areas.',
            'expense_date' => '2026-09-28',
            'amount' => 8000,
        ]);

        Auth::logout();
    }
}
